version: '4.17.0'

services:
  jumprpak-db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3506:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jumprpak
      MYSQL_USER: jumprpak
      MYSQL_PASSWORD: jumprpak
    volumes:
      - './database/migrations:/docker-entrypoint-initdb.d'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
